# Initialization

In [1]:
import logging

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
%matplotlib inline
%config InlineBackend.figure_format = 'png'
%config InlineBackend.figure_format = 'retina'

# Загрузка данных

In [2]:
items = pd.read_parquet("items.par")
events = pd.read_parquet("events.par")

In [37]:
items1 = pd.read_parquet("items.par")
items1.head(5)

,item_id,author,title,description,genre_and_votes,num_pages,average_rating,ratings_count,text_reviews_count,publisher,publication_year,country_code,language_code,format,is_ebook,isbn,isbn13,genre_and_votes_dict,genre_and_votes_str
3,6066819,Jennifer Weiner,Best Friends Forever,Addie Downs and Valerie Adler were eight when ...,"{'Womens Fiction-Chick Lit': 739, 'Fiction': 442}",368,3.49,51184,3282,Atria Books,2009,US,eng,Hardcover,False,0743294297,9780743294294,"{'Academic': None, 'Academic-Academia': None, ...","Womens Fiction-Chick Lit 739, Fiction 442"
6,378460,Michael Halberstam,The Wanting of Levine,,"{'Politics': 1, 'Humor': 1}",<NA>,4.38,12,4,Berkley Publishing Group,1979,US,,Paperback,False,0425040887,9780425040881,"{'Academic': None, 'Academic-Academia': None, ...","Politics 1user, Humor 1user"
15,89375,"Don Piper, Cecil Murphey",90 Minutes in Heaven: A True Story of Death an...,As he is driving home from a minister's confer...,"{'Christian': 395, 'Nonfiction': 392, 'Religio...",<NA>,3.91,68157,2885,,<NA>,US,,,False,0800759494,9780800759490,"{'Academic': None, 'Academic-Academia': None, ...","Christian 395, Nonfiction 392, Religion 142, S..."
16,89376,Randy Alcorn,Heaven,What is Heaven really going to be like? What w...,"{'Christian': 225, 'Religion-Theology': 154, '...",533,4.26,7345,566,,<NA>,US,eng,,False,0842379428,9780842379427,"{'Academic': None, 'Academic-Academia': None, ...","Christian 225, Religion-Theology 154, Nonficti..."
17,89377,Jennifer L. Holm,Penny from Heaven,It's 1953 and 11-year-old Penny dreams of a su...,"{'Historical-Historical Fiction': 284, 'Childr...",288,3.98,6949,615,Random House Books for Young Readers,2006,US,,Hardcover,False,037583687X,9780375836879,"{'Academic': None, 'Academic-Academia': None, ...","Historical-Historical Fiction 284, Childrens-M..."

# Разбиение с учётом хронологии

Рекомендательные системы на практике работают с учётом хронологии. Поэтому поток событий для тренировки и валидации полезно делить на то, что уже случилось, и что ещё случится. Это позволяет проводить валидацию на тех же пользователях, на которых тренировались, но на их событиях в будущем.

# === Знакомство: "холодный" старт

In [3]:
# точка разбиения
train_test_global_time_split_date = pd.to_datetime("2017-08-01").date()

train_test_global_time_split_idx = events["started_at"] < train_test_global_time_split_date

events_train = events[train_test_global_time_split_idx]
events_test = events[~train_test_global_time_split_idx]

# количество пользователей в train и test
users_train = events_train["user_id"].drop_duplicates()
users_test = events_test["user_id"].drop_duplicates()
# количество пользователей, которые есть и в train, и в test
common_users = set(users_train).intersection(set(users_test))

print(len(users_train), len(users_test), len(common_users))

428220 123223 120858

In [14]:
# «Холодные» пользователи — те, которые есть в test, но отсутствуют в train
cold_users = pd.Index(users_test).difference(pd.Index(users_train))
print(len(cold_users))

2365

### топ-100 наиболее популярных книг (учитывая и их среднюю оценку) за последние несколько лет. Например, с 2015 года и со средней оценкой не меньше 4. Их вы и будете рекомендовать «холодным» пользователям. Имея такие рекомендации, назовём их ещё и рекомендациями по умолчанию (англ. default recommendations).

In [31]:
from sklearn.preprocessing import MinMaxScaler

top_pop_start_date = pd.to_datetime("2015-01-01").date()

item_popularity = events_train \
    .query("started_at >= @top_pop_start_date") \
    .groupby(["item_id"]).agg(users=("user_id", "nunique"), avg_rating=("rating", "mean")).reset_index()

# нормализация пользователей и среднего рейтинга, требуется для их приведения к одному масштабу
scaler = MinMaxScaler()
item_popularity[["users_norm", "avg_rating_norm"]] = scaler.fit_transform(
    item_popularity[["users", "avg_rating"]]
)

# вычисляем popularity_score, как скор популярности со штрафом за низкий рейтинг
item_popularity["popularity_score"] = (
    item_popularity["users_norm"] * item_popularity["avg_rating_norm"]
)

# сортируем по убыванию popularity_score
item_popularity = item_popularity.sort_values("popularity_score", ascending=False)

# выбираем первые 100 айтемов со средней оценкой avg_rating не меньше 4
top_k_pop_items = item_popularity[item_popularity['avg_rating']>=4].head(100)

In [33]:
# добавляем информацию о книгах
top_k_pop_items = top_k_pop_items.merge(
    items.set_index("item_id")[["author", "title", "genre_and_votes", "publication_year"]], on="item_id")

with pd.option_context('display.max_rows', 100):
    display(top_k_pop_items[["item_id", "author", "title", "publication_year", "users", "avg_rating", "popularity_score", "genre_and_votes"]])

,item_id,author,title,publication_year,users,avg_rating,popularity_score,genre_and_votes
0,18007564,Andy Weir,The Martian,2014,20207,4.321275,0.412333,"{'Science Fiction': 11966, 'Fiction': 8430}"
1,18143977,Anthony Doerr,All the Light We Cannot See,2014,19462,4.290669,0.393471,"{'Historical-Historical Fiction': 13679, 'Fict..."
2,3,"J.K. Rowling, Mary GrandPré",Harry Potter and the Sorcerer's Stone (Harry P...,1997,15139,4.706057,0.344702,"{'Fantasy': 59818, 'Fiction': 17918, 'Young Ad..."
3,16096824,Sarah J. Maas,A Court of Thorns and Roses (A Court of Thorns...,2015,16770,4.301014,0.340108,"{'Fantasy': 14326, 'Young Adult': 4662, 'Roman..."
4,15881,"J.K. Rowling, Mary GrandPré",Harry Potter and the Chamber of Secrets (Harry...,1999,13043,4.632447,0.291076,"{'Fantasy': 50130, 'Young Adult': 15202, 'Fict..."
5,38447,Margaret Atwood,The Handmaid's Tale,1998,14611,4.232770,0.290194,"{'Fiction': 15424, 'Classics': 9937, 'Science ..."
6,11235712,Marissa Meyer,"Cinder (The Lunar Chronicles, #1)",2012,14348,4.179189,0.280247,"{'Young Adult': 10539, 'Fantasy': 9237, 'Scien..."
7,17927395,Sarah J. Maas,A Court of Mist and Fury (A Court of Thorns an...,2016,12177,4.730640,0.279094,"{'Fantasy': 10186, 'Romance': 3346, 'Young Adu..."
8,5,"J.K. Rowling, Mary GrandPré",Harry Potter and the Prisoner of Azkaban (Harr...,2004,11890,4.770143,0.275401,"{'Fantasy': 49784, 'Young Adult': 15393, 'Fict..."
9,13206900,Marissa Meyer,"Winter (The Lunar Chronicles, #4)",2015,12291,4.534293,0.266881,"{'Fantasy': 4835, 'Young Adult': 4672, 'Scienc..."
10,21853621,Kristin Hannah,The Nightingale,2015,12294,4.528144,0.266482,"{'Historical-Historical Fiction': 10105, 'Fict..."
11,18692431,"Nicola Yoon, David Yoon","Everything, Everything",2015,14121,4.071454,0.266466,"{'Young Adult': 5175, 'Romance': 3234, 'Contem..."
12,6,"J.K. Rowling, Mary GrandPré",Harry Potter and the Goblet of Fire (Harry Pot...,2002,10679,4.764772,0.246997,"{'Fantasy': 48257, 'Young Adult': 15483, 'Fict..."
13,16068905,Rainbow Rowell,Fangirl,2013,12642,4.119839,0.242313,"{'Young Adult': 9301, 'Contemporary': 5760, 'R..."
14,23437156,Leigh Bardugo,"Six of Crows (Six of Crows, #1)",2015,11138,4.512300,0.240338,"{'Fantasy': 15409, 'Young Adult': 6520}"
15,9969571,Ernest Cline,Ready Player One,2011,11812,4.290044,0.238754,"{'Science Fiction': 10560, 'Fiction': 7713, 'Y..."
16,17167166,Sarah J. Maas,"Crown of Midnight (Throne of Glass, #2)",2013,11025,4.509751,0.237727,"{'Fantasy': 11344, 'Young Adult': 4695, 'Roman..."
17,15745753,Rainbow Rowell,Eleanor & Park,2013,12410,4.046575,0.232280,"{'Young Adult': 11593, 'Romance': 6881, 'Conte..."
18,13206760,Marissa Meyer,"Scarlet (The Lunar Chronicles, #2)",2013,11514,4.262376,0.230773,"{'Young Adult': 6930, 'Fantasy': 6267, 'Scienc..."
19,13206828,Marissa Meyer,"Cress (The Lunar Chronicles, #3)",2014,10605,4.487977,0.227251,"{'Young Adult': 5813, 'Fantasy': 5413, 'Scienc..."
20,18006496,Sarah J. Maas,"Queen of Shadows (Throne of Glass, #4)",2015,10241,4.610097,0.227134,"{'Fantasy': 8435, 'Young Adult': 3170, 'Romanc..."
21,20613470,Sarah J. Maas,"Heir of Fire (Throne of Glass, #3)",2014,10133,4.495608,0.217611,"{'Fantasy': 9677, 'Young Adult': 3800, 'Romanc..."
22,2657,Harper Lee,To Kill a Mockingbird,2006,10188,4.459069,0.216505,"{'Classics': 41773, 'Fiction': 21733, 'Histori..."
23,2,"J.K. Rowling, Mary GrandPré",Harry Potter and the Order of the Phoenix (Har...,2004,9528,4.685873,0.215754,"{'Fantasy': 46485, 'Young Adult': 15194, 'Fict..."
24,18774964,"Fredrik Backman, Henning Koch",A Man Called Ove,2014,10024,4.394852,0.209065,"{'Fiction': 7091, 'Contemporary': 1656, 'Audio..."
25,18460392,Jennifer Niven,All the Bright Places,2015,10870,4.122355,0.208514,"{'Young Adult': 4691, 'Contemporary': 2534, 'R..."
26,7896527,Sarah J. Maas,"Throne of Glass (Throne of Glass, #1)",2012,10329,4.219866,0.204323,"{'Fantasy': 16888, 'Young Adult': 7306, 'Roman..."
27,1,J.K. Rowling,Harry Potter and the Half-Blood Prince (Harry ...,2006,8728,4.796059,0.203545,"{'Fantasy': 46400, 'Young Adult': 15083, 'Fict..."
28,20170404,Emily St. John Mandel,Station Eleven,2014,10511,4.127961,0.201989,"{'Fiction': 5860, 'Science Fiction': 3274, 'Sc..."
29,136251,J.K. Rowling,Harry Potter and the Deathly Hallows (Harry Po...,2007,8390,4.850775,0.198482,"{'Fantasy': 46667, 'Young Adult': 15403, 'Fict..."
30,16101128,Rick Yancey,"The 5th Wave (The 5th Wave, #1)",2013,9383,4.035809,0.174998,"{'Young Adult': 5331, 'Science Fiction': 3197,..."
31,5470,"George Orwell, Erich Fromm",1984,1950,9059,4.124738,0.173904,"{'Classics': 33441, 'Fiction': 21086, 'Science..."
32,19063,Markus Zusak,The Book Thief,<NA>,8085,4.479530,0.172826,"{'Historical-Historical Fiction': 18340, 'Fict..."
33,23395680,"Amie Kaufman, Jay Kristoff","Illuminae (The Illuminae Files, #1)",2015,8170,4.380416,0.169669,"{'Science Fiction': 3927, 'Young Adult': 3535,..."
34,25494343,Cassandra Clare,"Lady Midnight (The Dark Artifices, #1)",2016,7717,4.558248,0.168691,"{'Fantasy': 4277, 'Young Adult': 2491, 'Romanc..."
35,22055262,V.E. Schwab,"A Darker Shade of Magic (Shades of Magic, #1)",2015,8660,4.138684,0.166985,"{'Fantasy': 14539, 'Young Adult': 2101, 'Ficti..."
36,28260587,Sarah J. Maas,"Empire of Storms (Throne of Glass, #5)",2016,7416,4.557174,0.162061,"{'Fantasy': 6616, 'Young Adult': 2251, 'Romanc..."
37,23766634,Sarah J. Maas,A Court of Wings and Ruin (A Court of Thorns a...,2017,7455,4.490677,0.159868,"{'Fantasy': 7960, 'Romance': 2365, 'Young Adul..."
38,18798983,Renée Ahdieh,The Wrath and the Dawn (The Wrath and the Dawn...,2015,7887,4.255610,0.157744,"{'Fantasy': 5942, 'Young Adult': 3448, 'Romanc..."
39,27362503,Colleen Hoover,It Ends with Us,<NA>,7268,4.523115,0.157306,"{'Romance': 3077, 'Contemporary': 1673, 'New A..."
40,17675462,Maggie Stiefvater,"The Raven Boys (The Raven Cycle, #1)",2012,8049,4.096658,0.153124,"{'Fantasy': 9481, 'Young Adult': 7067, 'Fantas..."
41,23513349,Rupi Kaur,Milk and Honey,2014,7720,4.161788,0.149954,"{'Poetry': 14490, 'Feminism': 1105, 'Nonfictio..."
42,9361589,Erin Morgenstern,The Night Circus,2011,7361,4.085858,0.139546,"{'Fantasy': 16749, 'Fiction': 7058, 'Romance':..."
43,18635016,Kiera Cass,"The One (The Selection, #3)",2014,7340,4.073025,0.138569,"{'Young Adult': 4782, 'Romance': 3852, 'Scienc..."
44,15749186,Jenny Han,To All the Boys I've Loved Before (To All the ...,2015,7189,4.070942,0.135626,"{'Young Adult': 5919, 'Romance': 4965, 'Contem..."
45,22489107,Marissa Meyer,"Fairest (The Lunar Chronicles, #3.5)",2015,7254,4.040805,0.135509,"{'Fantasy': 2825, 'Young Adult': 2772, 'Scienc..."
46,10964,Diana Gabaldon,"Outlander (Outlander, #1)",2005,7002,4.126107,0.134470,"{'Historical-Historical Fiction': 10725, 'Roma..."
47,10194157,Leigh Bardugo,"Shadow and Bone (The Grisha, #1)",2012,7120,4.058567,0.133783,"{'Fantasy': 14290, 'Young Adult': 6921, 'Roman..."
48,20698530,Jenny Han,P.S. I Still Love You (To All the Boys I've Lo...,2015,6918,4.109858,0.132166,"{'Young Adult': 3659, 'Romance': 3112, 'Contem..."
49,27833670,Blake Crouch,Dark Matter,2016,6747,4.121980,0.129402,"{'Science Fiction': 4244, 'Fiction': 3079, 'Th..."
50,22544764,Naomi Novik,Uprooted,2015,6728,4.107164,0.128425,"{'Fantasy': 13419, 'Young Adult': 2048, 'Ficti..."
51,28187,Rick Riordan,The Lightning Thief (Percy Jackson and the Oly...,2006,6445,4.208534,0.127036,"{'Fantasy': 21419, 'Young Adult': 9587, 'Fanta..."
52,23164983,Ransom Riggs,Hollow City (Miss Peregrine’s Peculiar Childre...,<NA>,6639,4.041723,0.124057,"{'Fantasy': 4427, 'Young Adult': 3025, 'Fictio..."
53,15839976,Pierce Brown,"Red Rising (Red Rising, #1)",2014,6399,4.150180,0.123835,"{'Science Fiction': 4634, 'Fantasy': 2920, 'Yo..."
54,25489625,Ta-Nehisi Coates,Between the World and Me,2015,5762,4.470149,0.122831,"{'Nonfiction': 6587, 'Autobiography-Memoir': 2..."
55,32075671,Angie Thomas,The Hate U Give,2017,5385,4.707335,0.122639,"{'Young Adult': 8354, 'Fiction': 5014, 'Contem..."
56,28763485,Nicola Yoon,The Sun Is Also a Star,2016,6221,4.194663,0.122090,"{'Young Adult': 3806, 'Romance': 2512, 'Contem..."
57,22738563,Chimamanda Ngozi Adichie,We Should All Be Feminists,2014,5555,4.568317,0.121768,"{'Nonfiction': 6864, 'Feminism': 4519, 'Writin..."
58,13496,George R.R. Martin,"A Game of Thrones (A Song of Ice and Fire, #1)",2005,5699,4.440779,0.120460,"{'Fantasy': 44086, 'Fiction': 10111, 'Fantasy-..."
59,25111004,Colleen Hoover,November 9,2015,5806,4.366345,0.120067,"{'Romance': 1811, 'New Adult': 1296, 'Contempo..."
60,7171637,Cassandra Clare,"Clockwork Angel (The Infernal Devices, #1)",2010,5869,4.261714,0.117598,"{'Fantasy': 10151, 'Young Adult': 7424, 'Fanta..."
61,1885,"Jane Austen, Anna Quindlen",Pride and Prejudice,2000,5700,4.316316,0.116123,"{'Classics': 46807, 'Fiction': 14324, 'Romance..."
62,7613,"George Orwell, Boris Grabnar, Peter Škerl",Animal Farm,2003,5908,4.189235,0.115749,"{'Classics': 30122, 'Fiction': 17416, 'Science..."
63,186074,Patrick Rothfuss,The Name of the Wind (The Kingkiller Chronicle...,2007,5530,4.406510,0.115723,"{'Fantasy': 28188, 'Fiction': 4251, 'Fantasy-E..."
64,1582996,Cassandra Clare,"City of Ashes (The Mortal Instruments, #2)",2008,6050,4.083140,0.114588,"{'Fantasy': 11997, 'Young Adult': 9281, 'Fanta..."
65,13335037,Veronica Roth,"Divergent (Divergent, #1)",2012,5929,4.130882,0.114035,"{'Young Adult': 20260, 'Science Fiction-Dystop..."
66,3777732,Cassandra Clare,"City of Glass (The Mortal Instruments, #3)",<NA>,5469,4.365332,0.113063,"{'Fantasy': 11194, 'Young Adult': 8549, 'Fanta..."
67,30555488,Colson Whitehead,The Underground Railroad,2016,6050,4.029752,0.112604,"{'Historical-Historical Fiction': 5191, 'Ficti..."
68,11870085,John Green,The Fault in Our Stars,2012,5819,4.130091,0.111891,"{'Young Adult': 20449, 'Fiction': 10338, 'Roma..."
69,15704307,"Brian K. Vaughan, Fiona Staples","Saga, Vol. 1 (Saga, #1)",2012,5322,4.410936,0.111514,"{'Sequential Art-Graphic Novels': 7803, 'Seque..."
70,17378508,Maggie Stiefvater,"Blue Lily, Lily Blue (The Raven Cycle, #3)",2014,5284,4.335541,0.108270,"{'Fantasy': 5121, 'Young Adult': 3651, 'Fantas..."
71,23848559,Jenny Lawson,Furiously Happy: A Funny Book About Horrible T...,2015,5592,4.065629,0.105311,"{'Nonfiction': 3138, 'Humor': 1914, 'Autobiogr..."
72,10025305,Cassandra Clare,"Clockwork Prince (The Infernal Devices, #2)",2011,4900,4.491224,0.105087,"{'Fantasy': 7212, 'Young Adult': 5170, 'Romanc..."
73,8755785,Cassandra Clare,"City of Heavenly Fire (The Mortal Instruments,...",2014,4933,4.461788,0.104903,"{'Fantasy': 5999, 'Young Adult': 4162, 'Fantas..."
74,18335634,Cassandra Clare,"Clockwork Princess (The Infernal Devices, #3)",2013,4632,4.644214,0.103691,"{'Fantasy': 6538, 'Young Adult': 4566, 'Romanc..."
75,17851885,"Malala Yousafzai, Christina Lamb",I Am Malala: The Story of the Girl Who Stood U...,2013,5251,4.190821,0.102926,"{'Nonfiction': 5580, 'Biography': 2294, 'Autob..."
76,17788401,Colleen Hoover,Ugly Love,2014,5189,4.222779,0.102729,"{'Romance': 2972, 'New Adult': 2006, 'Contempo..."
77,18243700,Sarah J. Maas,"The Assassin's Blade (Throne of Glass, #0.1-0.5)",2014,4795,4.444004,0.101444,"{'Fantasy': 4943, 'Young Adult': 2078, 'Romanc..."
78,25899336,Paul Kalanithi,When Breath Becomes Air,<NA>,4798,4.427261,0.101014,"{'Nonfiction': 5848, 'Autobiography-Memoir': 3..."
79,18584855,Marissa Meyer,Heartless,2016,5264,4.071619,0.099326,"{'Fantasy': 4654, 'Young Adult': 2581, 'Retell..."
80,28587957,Jodi Picoult,Small Great Things,2016,4832,4.336921,0.099048,"{'Fiction': 2506, 'Contemporary': 576, 'Audiob..."
81,25614492,Ruta Sepetys,Salt to the Sea,2016,4655,4.423631,0.097899,"{'Historical-Historical Fiction': 5528, 'Young..."
82,6936382,Stephanie Perkins,Anna and the French Kiss (Anna and the French ...,2010,5050,4.108713,0.096438,"{'Young Adult': 6126, 'Romance': 5253, 'Contem..."
83,14061955,Leigh Bardugo,"Siege and Storm (The Grisha, #2)",2013,5194,4.003851,0.095843,"{'Fantasy': 8707, 'Young Adult': 4242, 'Romanc..."
84,24378015,"Colleen Hoover, Tarryn Fisher","Never Never (Never Never, #1)",<NA>,4942,4.156414,0.095823,"{'Romance': 1111, 'Young Adult': 954, 'Contemp..."
85,15724396,Rick Riordan,The Sword of Summer (Magnus Chase and the Gods...,2015,4825,4.224870,0.095583,"{'Fantasy': 4007, 'Fantasy-Mythology': 1823, '..."
86,18214414,Robert Galbraith,"The Silkworm (Cormoran Strike, #2)",2014,5101,4.042933,0.095351,"{'Mystery': 4585, 'Fiction': 2232, 'Mystery-Cr..."
87,77203,"Khaled Hosseini, Berliani M. Nugrahani",The Kite Runner,2004,4494,4.413663,0.094237,"{'Fiction': 14993, 'Historical-Historical Fict..."
88,17131869,"Brian K. Vaughan, Fiona Staples","Saga, Vol. 2 (Saga, #2)",2013,4355,4.516648,0.094076,"{'Sequential Art-Graphic Novels': 5510, 'Seque..."
89,27071490,Yaa Gyasi,Homegoing,2016,4376,4.499086,0.094058,"{'Historical-Historical Fiction': 3664, 'Ficti..."
90,15796700,"Chimamanda Ngozi Adichie, Jashar Awan",Americanah,2013,4564,4.343120,0.093727,"{'Fiction': 5255, 'Cultural-Africa': 1270, 'Co..."
91,23093367,"Brian K. Vaughan, Fiona Staples","Saga, Vol. 4 (Saga, #4)",2014,4329,4.454377,0.091859,"{'Sequential Art-Graphic Novels': 4243, 'Seque..."
92,2767052,Suzanne Collins,"The Hunger Games (The Hunger Games, #1)",2008,4361,4.413437,0.091441,"{'Young Adult': 30042, 'Fiction': 16754, 'Scie..."
93,15818107,"Christina Baker Kline, Christina Baker Kline",Orphan Train,2013,4748,4.119419,0.090982,"{'Historical-Historical Fiction': 4762, 'Ficti..."
94,14061957,Leigh Bardugo,"Ruin and Rising (The Grisha, #3)",2014,4656,4.176332,0.090847,"{'Fantasy': 7376, 'Young Adult': 3542, 'Romanc..."
95,8490112,Laini Taylor,Daughter of Smoke & Bone (Daughter of Smoke & ...,2011,4792,4.080968,0.090694,"{'Fantasy': 11681, 'Young Adult': 7110, 'Roman..."
96,18966819,Pierce Brown,"Golden Son (Red Rising, #2)",2015,4361,4.374914,0.090409,"{'Science Fiction': 2613, 'Fantasy': 1372, 'Sc..."
97,3636,Lois Lowry,"The Giver (The Giver, #1)",2006,4667,4.098564,0.088832,"{'Young Adult': 10993, 'Fiction': 9045, 'Class..."
98,18293427,Gabrielle Zevin,The Storied Life of A.J. Fikry,2014,4674,4.092640,0.088795,"{'Fiction': 3795, 'Contemporary': 1100, 'Writi..."
99,26252859,Rick Riordan,"The Hidden Oracle (The Trials of Apollo, #1)",2016,4371,4.293068,0.088419,"{'Fantasy': 3173, 'Fantasy-Mythology': 1514}"

In [36]:
# Завершите предлагаемый код, чтобы в cold_users_events_with_recs для каждого события получить столбец avg_rating. 
# В нём при совпадении по item_id будет значение из одноимённого столбца из top_k_pop_items, иначе — пропуск.

cold_users_events_with_recs = \
    events_test[events_test["user_id"].isin(cold_users)] \
    .merge(top_k_pop_items, on="item_id", how="left")

cold_user_items_no_avg_rating_idx = cold_users_events_with_recs["avg_rating"].isnull()
cold_user_recs = cold_users_events_with_recs[~cold_user_items_no_avg_rating_idx] \
    [["user_id", "item_id", "rating", "avg_rating"]]

In [47]:
# посчитаем метрики рекомендаций
from sklearn.metrics import mean_squared_error, mean_absolute_error

rmse = mean_squared_error(cold_user_recs["rating"], cold_user_recs["avg_rating"], squared=False)
mae = mean_absolute_error(cold_user_recs["rating"], cold_user_recs["avg_rating"])
print(round(rmse, 2), round(mae, 2))

0.78 0.62

In [48]:
# посчитаем покрытие холодных пользователей рекомендациями

cold_users_hit_ratio = cold_users_events_with_recs.groupby("user_id").agg(hits=("avg_rating", lambda x: (~x.isnull()).mean()))

print(f"Доля пользователей без релевантных рекомендаций: {(cold_users_hit_ratio == 0).mean().iat[0]:.2f}")
print(f"Среднее покрытие пользователей: {cold_users_hit_ratio[cold_users_hit_ratio != 0].mean().iat[0]:.2f}")

Доля пользователей без релевантных рекомендаций: 0.59
Среднее покрытие пользователей: 0.44

# === Знакомство: первые персональные рекомендации

In [25]:
# Степень разреженности матрицы взаимодействий (index='user_id', columns='item_id', values='rating')
# Классное решение. но... 
# pivot_df = events.pivot(index='user_id', columns='item_id', values='rating') # MemoryError: Unable to allocate 134. GiB for an array with shape (430585, 41673) and data type float64
# 11751086 
1 - events[['user_id', 'item_id', 'rating']].shape[0]/ (len(events['user_id'].unique()) * len(events['item_id'].unique()))

0.9993451160571009

In [29]:
from surprise import Dataset, Reader
from surprise import SVD

# используем Reader из библиотеки surprise для преобразования событий (events)
# в формат, необходимый surprise
reader = Reader(rating_scale=(1, 5))
surprise_train_set = Dataset.load_from_df(events_train[['user_id', 'item_id', 'rating']], reader)
surprise_train_set = surprise_train_set.build_full_trainset()

# инициализируем модель
svd_model = SVD(n_factors=100, random_state=0)

# обучаем модель
svd_model.fit(surprise_train_set)

In [30]:
surprise_test_set = list(events_test[['user_id', 'item_id', 'rating']].itertuples(index=False))

# получаем рекомендации для тестовой выборки
svd_predictions = svd_model.test(surprise_test_set)

In [31]:
# Оценка рекомендаций
from surprise import accuracy

rmse = accuracy.rmse(svd_predictions)
mae = accuracy.mae(svd_predictions)
                     
print(rmse, mae)

RMSE: 0.8263
MAE:  0.6460
0.826346375350908 0.6460143973270805

In [34]:
# Проверка метрик на адекватность

from surprise import NormalPredictor

# инициализируем состояние генератора, это необходимо для получения
# одной и той же последовательности случайных чисел, только в учебных целях
np.random.seed(0)

random_model = NormalPredictor()

random_model.fit(surprise_train_set)
random_predictions = random_model.test(surprise_test_set)

rmse_r = accuracy.rmse(random_predictions)
mae_r = accuracy.mae(random_predictions)
                     
print(rmse_r, mae_r)

RMSE: 1.2590
MAE:  0.9982
1.2590325375790072 0.9982060614713011

In [54]:
def get_recommendations_svd(user_id, all_items, events, model, include_seen=True, n=5):
#def get_recommendations_svd(user_id, events, model, include_seen=True, n=5):

    """ возвращает n рекомендаций для user_id """
    
    # получим список идентификаторов всех книг
    all_items = set(events['item_id'].unique())
        
    # учитываем флаг, стоит ли уже прочитанные книги включать в рекомендации
    if include_seen:
        items_to_predict = list(all_items)
    else:
        # получим список книг, которые пользователь уже прочитал ("видел")
        seen_items = set(events[events['user_id']==user_id]['item_id'].unique())
        
        # книги, которые пользователь ещё не читал
        # только их и будем включать в рекомендации
        items_to_predict = list(all_items - seen_items)
    
    # получаем скоры для списка книг, т. е. рекомендации
    predictions = [model.predict(user_id, item_id) for item_id in items_to_predict]
    
    # сортируем рекомендации по убыванию скора и берём только n первых
    recommendations = sorted(predictions, key=lambda x: x.est, reverse=True)[:n]
    
    return pd.DataFrame([(pred.iid, pred.est) for pred in recommendations], columns=["item_id", "score"])

In [55]:
get_recommendations_svd(1296647, items, events_test, svd_model)

    item_id     score
0   8471387  5.000000
1    481749  5.000000
2  30688013  4.996900
3   6898978  4.969303
4  24019187  4.964964

In [56]:
# выберем произвольного пользователя из тренировочной выборки ("прошлого")
user_id = events_train['user_id'].sample().iat[0]

print(f"user_id: {user_id}")

print("История (последние события, recent)")
user_history = (
    events_train
    .query("user_id == @user_id")
    .merge(items.set_index("item_id")[["author", "title", "genre_and_votes"]], on="item_id")
)
user_history_to_print = user_history[["author", "title", "started_at", "read_at", "rating", "genre_and_votes"]].tail(10)
display(user_history_to_print)

print("Рекомендации")
user_recommendations = get_recommendations_svd(user_id, items, events_train, svd_model)
user_recommendations = user_recommendations.merge(items[["item_id", "author", "title", "genre_and_votes"]], on="item_id")
display(user_recommendations)

user_id: 1109853
История (последние события, recent)

,author,title,started_at,read_at,rating,genre_and_votes
0,Patrick Rothfuss,"The Wise Man's Fear (The Kingkiller Chronicle,...",2015-06-17,2015-08-31,5,"{'Fantasy': 16491, 'Fiction': 2222, 'Fantasy-E..."
1,Andy Weir,The Martian,2014-12-07,2014-12-11,4,"{'Science Fiction': 11966, 'Fiction': 8430}"
2,Brandon Sanderson,"The Way of Kings (The Stormlight Archive, #1)",2015-08-31,2015-10-30,5,"{'Fantasy': 14291, 'Fiction': 1623, 'Fantasy-E..."
3,Brandon Sanderson,"Words of Radiance (The Stormlight Archive, #2)",2015-10-30,2016-03-17,5,"{'Fantasy': 8542, 'Fiction': 872, 'Fantasy-Epi..."
4,Ken Follett,"Fall of Giants (The Century Trilogy, #1)",2016-05-12,2016-08-30,4,"{'Historical-Historical Fiction': 4665, 'Ficti..."

Рекомендации

,item_id,score,author,title,genre_and_votes
0,30688013,5.000000,Robin Hobb,"Assassin's Fate (The Fitz and the Fool, #3)","{'Fantasy': 1657, 'Fiction': 172, 'Fantasy-Epi..."
1,11221285,5.000000,Brandon Sanderson,"The Way of Kings, Part 2 (The Stormlight Archi...","{'Fantasy': 641, 'Fiction': 46, 'Fantasy-Epic ..."
2,19219646,5.000000,Wolfgang Herrndorf,Arbeit und Struktur,"{'Nonfiction': 25, 'European Literature-German..."
3,22037424,4.996202,"J.K. Rowling, Jonny Duddle, Tomislav Tomić",Harry Potter and the Prisoner of Azkaban (Harr...,"{'Fantasy': 49994, 'Young Adult': 15433, 'Fict..."
4,2168850,4.995777,"محمد بن إدريس الشافعي, إميل بديع يعقوب",ديوان الإمام الشافعي,"{'Poetry': 93, 'Religion': 15, 'Literature': 1..."

# === Базовые подходы: коллаборативная фильтрация

In [4]:
import scipy
import sklearn.preprocessing

# перекодируем идентификаторы пользователей: 
# из имеющихся в последовательность 0, 1, 2, ...
user_encoder = sklearn.preprocessing.LabelEncoder()
user_encoder.fit(events["user_id"])
events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])

# перекодируем идентификаторы объектов: 
# из имеющихся в последовательность 0, 1, 2, ...
item_encoder = sklearn.preprocessing.LabelEncoder()
item_encoder.fit(items["item_id"])
items["item_id_enc"] = item_encoder.transform(items["item_id"])
events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

/tmp/ipykernel_3141/1044897688.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["user_id_enc"] = user_encoder.transform(events_train["user_id"])
/tmp/ipykernel_3141/1044897688.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["user_id_enc"] = user_encoder.transform(events_test["user_id"])
/tmp/ipykernel_3141/1044897688.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["item_id_enc"] = item_encoder.transform(events_train["item_id"])
/tmp/ipykernel_3141/1044897688.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["item_id_enc"] = item_encoder.transform(events_test["item_id"])

In [61]:
events_train['item_id_enc'].sort_values()

6974830         0
5075879         0
7039618         0
7185591         0
6853066         0
            ...
3920366     43232
10967011    43232
3275687     43250
11146807    43304
1263206     43304
Name: item_id_enc, Length: 11326124, dtype: int64

In [7]:
# Перейдём к подготовке матрицы взаимодействий
#events.shape[0] * items.shape[0] / 1024 ** 3
print(len(events['user_id'].unique()))
print(len(events['item_id'].unique()))
len(events['user_id'].unique()) * len(events['item_id'].unique()) / 1024 ** 3

430585
41673

16.71143686864525

In [12]:
# создаём sparse-матрицу формата CSR 
user_item_matrix_train = scipy.sparse.csr_matrix((
    events_train["rating"],
    (events_train['user_id_enc'], events_train['item_id_enc'])),
    dtype=np.int8)

In [13]:
# Размеры памяти, требуемой для хранения матрицы взаимодействий, 
import sys
sum([sys.getsizeof(i) for i in user_item_matrix_train.data])/1024**3

0.26370687410235405

In [ ]:
#  код для создания и тренировки модели.
from implicit.als import AlternatingLeastSquares

als_model = AlternatingLeastSquares(factors=50, iterations=50, regularization=0.05, random_state=0)
als_model.fit(user_item_matrix_train)

 54%|███████████████████████████████████████████████████████████████████████████                                                                | 27/50 [01:45<01:29,  3.89s/it]

In [ ]:
# функция для получения рекомендации для пользователя с помощью модели ALS
def get_recommendations_als(user_item_matrix, model, user_id, user_encoder, item_encoder, include_seen=True, n=5):
    """
    Возвращает отранжированные рекомендации для заданного пользователя
    """
    user_id_enc = user_encoder.transform([user_id])[0]
    recommendations = model.recommend(
         user_id_enc, 
         user_item_matrix[user_id_enc], 
         filter_already_liked_items=not include_seen, # будет ли ALS-модель убирать из рекомендаций те объекты, которые пользователь уже видел
         N=n)
    recommendations = pd.DataFrame({"item_id_enc": recommendations[0], "score": recommendations[1]})
    recommendations["item_id"] = item_encoder.inverse_transform(recommendations["item_id_enc"])
    
    return recommendations

In [ ]:
# Получим рекомендации для всех имеющихся пользователей. 
# получаем список всех возможных user_id (перекодированных)
user_ids_encoded = range(len(user_encoder.classes_))

# получаем рекомендации для всех пользователей
als_recommendations = als_model.recommend(
    user_ids_encoded, 
    user_item_matrix_train[user_ids_encoded], 
    filter_already_liked_items=False, N=100)

In [ ]:
# Код возвращает рекомендации как список списков, это не очень удобно. Преобразуем его в более удобный формат — табличный
# преобразуем полученные рекомендации в табличный формат
item_ids_enc = als_recommendations[0]
als_scores = als_recommendations[1]

als_recommendations = pd.DataFrame({
    "user_id_enc": user_ids_encoded,
    "item_id_enc": item_ids_enc.tolist(), 
    "score": als_scores.tolist()})
als_recommendations = als_recommendations.explode(["item_id_enc", "score"], ignore_index=True)

# приводим типы данных
als_recommendations["item_id_enc"] = als_recommendations["item_id_enc"].astype("int")
als_recommendations["score"] = als_recommendations["score"].astype("float")

# получаем изначальные идентификаторы
als_recommendations["user_id"] = user_encoder.inverse_transform(als_recommendations["user_id_enc"])
als_recommendations["item_id"] = item_encoder.inverse_transform(als_recommendations["item_id_enc"])
als_recommendations = als_recommendations.drop(columns=["user_id_enc", "item_id_enc"])

### als_recommendations

In [14]:
# Сохраним полученные рекомендации в файл, они ещё нам пригодятся.
als_recommendations = als_recommendations[["user_id", "item_id", "score"]]
als_recommendations.to_parquet("als_recommendations.parquet")

In [5]:
als_recommendations = pd.read_parquet("als_recommendations.parquet")

In [6]:
# добавим в датафрейм с рекомендациями истинные оценки из тестовой выборки:
als_recommendations = (
    als_recommendations
    .merge(events_test[["user_id", "item_id", "rating"]]
               .rename(columns={"rating": "rating_test"}), 
           on=["user_id", "item_id"], how="left")
)

In [16]:
import sklearn.metrics

def compute_ndcg(rating: pd.Series, score: pd.Series, k):

    """ подсчёт метрики ndcg
    rating: истинные оценки
    score: оценки модели
    k: количество айтемов (по убыванию score) для оценки, остальные - отбрасываются
    """
    
    # если кол-во объектов меньше 2, то NDCG - не определена
    if len(rating) < 2:
        return np.nan

    ndcg = sklearn.metrics.ndcg_score(np.asarray([rating.to_numpy()]), np.asarray([score.to_numpy()]), k=k)

    return ndcg

In [17]:
# Умея считать NDCG для одного пользователя, посчитаем данную метрику, например, для k=5 для всех пользователей из тестовой выборки. 
# В результате каждому пользователю будет соответствовать одно значение NDCG@5. Запись “NDCG@5” означает, что метрика NDCG считается для пяти объектов

rating_test_idx = ~als_recommendations["rating_test"].isnull()
ndcg_at_5_scores = als_recommendations[rating_test_idx].groupby("user_id").apply(lambda x: compute_ndcg(x["rating_test"], x["score"], k=5))

In [18]:
# Имея ряд значений NDCG@5 по пользователям, можно посчитать среднее её значение (по всем пользователям):
print(ndcg_at_5_scores.mean())

0.975946709792109

# === Базовые подходы: контентные рекомендации

In [7]:
# преобразуем значения в genre_and_votes из текстового представления в тип Python:
items["genre_and_votes"] = items["genre_and_votes"].apply(eval)

In [65]:
items["genre_and_votes"].head(3)

3     {'Womens Fiction-Chick Lit': 739, 'Fiction': 442}
6                           {'Politics': 1, 'Humor': 1}
15    {'Christian': 395, 'Nonfiction': 392, 'Religio...
Name: genre_and_votes, dtype: object

In [8]:
def get_genres(items):

    """ 
    извлекает список жанров по всем книгам, 
    подсчитывает долю голосов по каждому их них
    """
    
    genres_counter = {}
    
    for k, v, in items.iterrows():
        genre_and_votes = v['genre_and_votes']
        if genre_and_votes is None or not isinstance(genre_and_votes, dict):
            continue
        for genre, votes in genre_and_votes.items():
            # увеличиваем счётчик жанров
            try:
                genres_counter[genre] += votes
            except KeyError:
                genres_counter[genre] = 0

    genres = pd.Series(genres_counter, name="votes")
    genres = genres.to_frame()
    genres = genres.reset_index().rename(columns={"index": "name"})
    genres.index.name = "genre_id"
    
    return genres
   
genres = get_genres(items)

In [67]:
items

,item_id,author,title,description,genre_and_votes,num_pages,average_rating,ratings_count,text_reviews_count,publisher,...,country_code,language_code,format,is_ebook,isbn,isbn13,genre_and_votes_dict,genre_and_votes_str,item_id_enc,age
3,6066819,Jennifer Weiner,Best Friends Forever,Addie Downs and Valerie Adler were eight when ...,"{'Womens Fiction-Chick Lit': 739, 'Fiction': 442}",368,3.49,51184,3282,Atria Books,...,US,eng,Hardcover,False,0743294297,9780743294294,"{'Academic': None, 'Academic-Academia': None, ...","Womens Fiction-Chick Lit 739, Fiction 442",23133,9.0
6,378460,Michael Halberstam,The Wanting of Levine,,"{'Politics': 1, 'Humor': 1}",<NA>,4.38,12,4,Berkley Publishing Group,...,US,,Paperback,False,0425040887,9780425040881,"{'Academic': None, 'Academic-Academia': None, ...","Politics 1user, Humor 1user",12687,39.0
15,89375,"Don Piper, Cecil Murphey",90 Minutes in Heaven: A True Story of Death an...,As he is driving home from a minister's confer...,"{'Christian': 395, 'Nonfiction': 392, 'Religio...",<NA>,3.91,68157,2885,,...,US,,,False,0800759494,9780800759490,"{'Academic': None, 'Academic-Academia': None, ...","Christian 395, Nonfiction 392, Religion 142, S...",6460,NaN
16,89376,Randy Alcorn,Heaven,What is Heaven really going to be like? What w...,"{'Christian': 225, 'Religion-Theology': 154, '...",533,4.26,7345,566,,...,US,eng,,False,0842379428,9780842379427,"{'Academic': None, 'Academic-Academia': None, ...","Christian 225, Religion-Theology 154, Nonficti...",6461,NaN
17,89377,Jennifer L. Holm,Penny from Heaven,It's 1953 and 11-year-old Penny dreams of a su...,"{'Historical-Historical Fiction': 284, 'Childr...",288,3.98,6949,615,Random House Books for Young Readers,...,US,,Hardcover,False,037583687X,9780375836879,"{'Academic': None, 'Academic-Academia': None, ...","Historical-Historical Fiction 284, Childrens-M...",6462,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2360257,279660,James Goldman,The Lion in Winter,Insecure siblings fighting for their parents' ...,"{'Plays': 294, 'Historical-Historical Fiction'...",103,4.22,8227,100,Random House,...,US,eng,Paperback,False,0812973356,9780812973358,"{'Academic': None, 'Academic-Academia': None, ...","Plays 294, Historical-Historical Fiction 110, ...",11240,14.0
2360258,7657484,"J. Michael Straczynski, Shane Davis, Sandra Ho...","Superman: Earth One, Volume 1",Forget everything you know about The Man of St...,"{'Sequential Art-Comics': 683, 'Sequential Art...",134,3.90,13221,578,DC Comics,...,US,eng,Hardcover,False,1401224687,9781401224684,"{'Academic': None, 'Academic-Academia': None, ...","Sequential Art-Comics 683, Sequential Art-Grap...",25871,8.0
2360322,7715664,Larissa Ione,Sin Undone (Demonica #5),HER TOUCH IS DEADLY\nAs the only female Seminu...,"{'Romance-Paranormal Romance': 703, 'Fantasy-P...",400,4.35,23091,819,Grand Central Publishing,...,US,eng,Mass Market Paperback,False,0446556815,9780446556811,"{'Academic': None, 'Academic-Academia': None, ...","Romance-Paranormal Romance 703, Fantasy-Parano...",25962,8.0
2360395,30367813,J.A. Owenby,The Truth She Knew (The Truth Series #1),"""A bittersweet story of young love, independen...","{'Fiction': 4, 'Romance': 3, 'Business-Amazon'...",238,4.34,111,67,,...,US,eng,Paperback,False,1533660549,9781533660541,"{'Academic': None, 'Academic-Academia': None, ...","Fiction 4, Romance 3, Business-Amazon 3",42220,2.0
2360448,282240,Geoffrey Huntington,"Demon Witch (The Ravenscliff, #2)",Devon March matches wits and wizardry against ...,"{'Fantasy': 33, 'Young Adult': 16, 'Horror': 1...",388,3.99,491,17,ReganBooks,...,US,,Paperback,False,0060595515,9780060595517,"{'Academic': None, 'Academic-Academia': None, ...","Fantasy 33, Young Adult 16, Horror 13, Fantasy...",11291,14.0

In [9]:
genres["score"] = genres["votes"] / genres["votes"].sum()
genres.sort_values(by="score", ascending=False).head(10)

                                   name    votes     score
genre_id
25                              Fantasy  6850060  0.149651
1                               Fiction  6406256  0.139955
38                             Classics  3414934  0.074605
18                          Young Adult  3296951  0.072027
34                              Romance  2422614  0.052926
5                            Nonfiction  1737406  0.037957
16        Historical-Historical Fiction  1531205  0.033452
20                              Mystery  1371196  0.029956
24                      Science Fiction  1218917  0.026629
33                   Fantasy-Paranormal   857012  0.018723

In [128]:
import scipy
import sklearn.preprocessing

# Функция строит матрицу вида «книга-жанр»
def get_item2genre_matrix(genres, items):

    genre_names_to_id = genres.reset_index().set_index("name")["genre_id"].to_dict()
    
    # list to build CSR matrix
    genres_csr_data = []
    genres_csr_row_idx = []
    genres_csr_col_idx = []
    
    for item_idx, (k, v) in enumerate(items.iterrows()):
        if v["genre_and_votes"] is None:
            continue
        for genre_name, votes in v["genre_and_votes"].items():
            genre_idx = genre_names_to_id[genre_name]
            genres_csr_data.append(int(votes))
            genres_csr_row_idx.append(item_idx)
            genres_csr_col_idx.append(genre_idx)

    genres_csr = scipy.sparse.csr_matrix((genres_csr_data, (genres_csr_row_idx, genres_csr_col_idx)), shape=(len(items), len(genres)))
    # нормализуем, чтобы сумма оценок принадлежности к жанру была равна 1
    genres_csr = sklearn.preprocessing.normalize(genres_csr, norm='l1', axis=1)
    
    return genres_csr

In [22]:
item2genre_matrix = get_item2genre_matrix(genres, items)
print("Ненулевые элементы:", item2genre_matrix.data)
print("Индексы столбцов:", item2genre_matrix.indices)
print("Позиции строк:", item2genre_matrix.indptr)

Ненулевые элементы: [0.6257409  0.3742591  0.5        ... 0.09459459 0.06756757 0.17567568]
Индексы столбцов: [ 0  1  2 ... 41 42 44]
Позиции строк: [     0      2      4 ... 210887 210890 210895]

In [129]:
# Получим матрицу с весами по жанрам для каждой книги - это поможет вычислить, какие книги «ближе» к пользовательскому вектору.
items = items.sort_values(by="item_id_enc")
all_items_genres_csr = get_item2genre_matrix(genres, items) #  матрица распределения интересов всех пользователей по жанрам. Строка — вектор распределения интересов всех пользователей по жанрам для одного объекта

In [29]:
# Аналогичным образом получим матрицу с весами по жанрам для какого-нибудь пользователя, например, для пользователя с идентификатором 1000010. 

user_id = 1000010
user_events = events_train.query("user_id == @user_id")[["item_id", "rating"]]
user_items = items[items["item_id"].isin(user_events["item_id"])]

user_items_genres_csr = get_item2genre_matrix(genres, user_items)
user_items_genres_csr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 149 stored elements and shape (22, 815)>

In [33]:
print("Ненулевые элементы:", user_items_genres_csr.data)
print("Индексы столбцов:", user_items_genres_csr.indices)
print("Позиции строк:", user_items_genres_csr.indptr)
print("Первые 10 ненулевых элементов:", user_items_genres_csr.data[:10])

Ненулевые элементы: [0.5940531  0.14343098 0.16086999 0.10164593 0.47986348 0.01756128
 0.17406143 0.02010549 0.01737512 0.04331368 0.13471921 0.03028235
 0.03363326 0.0490847  0.27864889 0.1997383  0.39293398 0.12867884
 0.25257534 0.02254324 0.11995113 0.01225385 0.40056777 0.01207417
 0.10006708 0.02481913 0.03434191 0.02080638 0.19117429 0.09960751
 0.66971465 0.03950355 0.27350777 0.0731807  0.53870264 0.0611202
 0.05348869 0.16767481 0.38419429 0.0583414  0.07267723 0.20030849
 0.04424752 0.01920518 0.01959835 0.01917493 0.01457779 0.20911553
 0.03138134 0.03978706 0.20556645 0.36237975 0.03698515 0.01923975
 0.05407677 0.0265247  0.01494349 0.43792751 0.16911707 0.04843148
 0.03962576 0.03876091 0.03538014 0.1011872  0.0422203  0.03231386
 0.05503577 0.07800951 0.11745335 0.03615075 0.5366996  0.23168679
 0.5061064  0.08859449 0.04905817 0.05775202 0.12067895 0.03477541
 0.04429725 0.03249845 0.03353343 0.03270544 0.31372261 0.25855829
 0.15145736 0.09719777 0.04266921 0.04010172 0.02736209 0.02552817
 0.02132238 0.0220804  0.31845629 0.52612234 0.15542137 0.18001667
 0.04354518 0.66119413 0.05508882 0.0601552  0.5554571  0.08019495
 0.02584552 0.0456358  0.03071924 0.07059519 0.07650273 0.05036184
 0.03485453 0.02983311 0.44303797 0.09748933 0.32128121 0.13819148
 0.55039869 0.03244054 0.11790363 0.05465822 0.03666599 0.04245894
 0.03414435 0.02923737 0.06747086 0.03462141 0.35139899 0.50227657
 0.08856576 0.05775868 0.13674148 0.10402565 0.59369434 0.0274908
 0.02547203 0.02565016 0.04542216 0.0125282  0.01620948 0.0127657
 0.35054022 0.20408163 0.242497   0.20288115 0.5747464  0.22851041
 0.19674319 0.15510845 0.12542808 0.67223174 0.04723174]
Индексы столбцов: [  1  18  20  52   5  37  53  55  57 111 131 132 133 150   1  24  38  67
   1   2  24  25  38  61  67  82 107 229   1  34  38 295   1  22  38 107
 233   1  20  21  23  38  45  46  55  61  82   5   8   9  37  38 107 141
 168 182 269   1  20  21  23  38  45  52  61  82 123   2   5  36  37  38
   1  21  23  44  52  61  68 123 131 188   1  20  21  23  45  46  52  61
  82 134   1  24  25   1  18  25  42  74   1  52  61  82 107 118 121 123
 134 188   5   8   9 125   1  20  52  55  61  71  82 107 123 134   1  16
  19 235   1  24  25  26  55  61  67 193 254 265  18  24  25  67   1  16
  38   1  24  25  67]
Позиции строк: [  0   4  14  18  28  32  37  47  57  67  72  82  92  95 100 110 114 124
 128 138 142 145 149]
Первые 10 ненулевых элементов: [0.5940531  0.14343098 0.16086999 0.10164593 0.47986348 0.01756128
 0.17406143 0.02010549 0.01737512 0.04331368]

In [34]:
# вычислим склонность пользователя к жанрам как среднее взвешенное значение популяции на его оценки книг.

# преобразуем пользовательские оценки из списка в вектор-столбец
user_ratings = user_events["rating"].to_numpy() / 5
user_ratings = np.expand_dims(user_ratings, axis=1)

user_items_genres_weighted = user_items_genres_csr.multiply(user_ratings)

user_genres_scores = np.asarray(user_items_genres_weighted.mean(axis=0)) #  вектор интересов пользователя по жанрам.

In [35]:
# выведем список жанров, которые предпочитает пользователь

user_genres = genres.copy()
user_genres["score"] = np.ravel(user_genres_scores)
user_genres = user_genres[user_genres["score"] > 0].sort_values(by=["score"], ascending=False)

user_genres.head(5)

                     name    votes     score
genre_id
1                 Fiction  6406256  0.195253
38               Classics  3414934  0.096687
25                Fantasy  6850060  0.074261
24        Science Fiction  1218917  0.045902
5              Nonfiction  1737406  0.044359

In [52]:
# Получите наиболее релевантные рекомендации для пользователя

from sklearn.metrics.pairwise import cosine_similarity

# вычисляем сходство между вектором пользователя и векторами по книгам
similarity_scores = cosine_similarity(all_items_genres_csr, user_genres_scores)

# преобразуем в одномерный массив
similarity_scores = similarity_scores.flatten()

# получаем индексы top-k (по убыванию значений), по сути, индексы книг (encoded)
k = 5
top_k_indices = np.argsort(similarity_scores)[::-1][0:k]

selected_items = items[items["item_id_enc"].isin(top_k_indices)]

with pd.option_context("max_colwidth", 100):
   display(selected_items[["author", "title", "genre_and_votes"]])

,author,title,genre_and_votes
564712,Ray Bradbury,"Farewell Summer (Green Town, #3)","{'Fiction': 170, 'Fantasy': 72, 'Science Fiction': 72, 'Classics': 52}"
1358935,John Fowles,The Magus,"{'Fiction': 1204, 'Classics': 421, 'Fantasy': 228, 'Mystery': 203, 'Literature': 167}"
80465,G.K. Chesterton,The Napoleon of Notting Hill,"{'Fiction': 166, 'Classics': 88, 'Fantasy': 44, 'Humor': 22, 'Literature': 20}"
1168335,Ray Bradbury,"Dandelion Wine (Green Town, #1)","{'Fiction': 1438, 'Classics': 914, 'Science Fiction': 529, 'Fantasy': 456, 'Young Adult': 212}"
2244467,Samuel Butler,"Erewhon (Erewhon , #1)","{'Fiction': 162, 'Classics': 139, 'Science Fiction': 60, 'Fantasy': 55}"

# === Базовые подходы: валидация

In [38]:
def process_events_recs_for_binary_metrics(events_train, events_test, recs, top_k=None):

    """
    размечает пары <user_id, item_id> для общего множества пользователей признаками
    - gt (ground truth) - объект есть в тестовой выборке;
    - pr (prediction) - объект есть в рекомендациях.
    top_k: расчёт ведётся только для top k-рекомендаций
    """

    events_test["gt"] = True
    common_users = set(events_test["user_id"]) & set(recs["user_id"])

    print(f"Common users: {len(common_users)}")
    
    events_for_common_users = events_test[events_test["user_id"].isin(common_users)].copy()
    recs_for_common_users = recs[recs["user_id"].isin(common_users)].copy()

    recs_for_common_users = recs_for_common_users.sort_values(["user_id", "score"], ascending=[True, False])

    # оставляет только те item_id, которые были в events_train, 
    # т. к. модель не имела никакой возможности давать рекомендации для новых айтемов
    events_for_common_users = events_for_common_users[events_for_common_users["item_id"].isin(events_train["item_id"].unique())]

    if top_k is not None:
        recs_for_common_users = recs_for_common_users.groupby("user_id").head(top_k)
    
    events_recs_common = events_for_common_users[["user_id", "item_id", "gt"]].merge(
        recs_for_common_users[["user_id", "item_id", "score"]], 
        on=["user_id", "item_id"], how="outer")    

    events_recs_common["gt"] = events_recs_common["gt"].fillna(False)
    events_recs_common["pr"] = ~events_recs_common["score"].isnull()
    
    events_recs_common["tp"] = events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fp"] = ~events_recs_common["gt"] & events_recs_common["pr"]
    events_recs_common["fn"] = events_recs_common["gt"] & ~events_recs_common["pr"]

    return events_recs_common

In [18]:
events_recs_for_binary_metrics = process_events_recs_for_binary_metrics(
  events_train,
    events_test, 
    als_recommendations, 
    top_k=10)

/tmp/ipykernel_6491/1848159129.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_test["gt"] = True

Common users: 123223

In [40]:
def compute_cls_metrics(events_recs_for_binary_metric):
    
    groupper = events_recs_for_binary_metric.groupby("user_id")

    # precision = tp / (tp + fp)
    precision = groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fp"].sum())
    precision = precision.fillna(0).mean()
    
    # recall = tp / (tp + fn)
    recall = groupper["tp"].sum()/(groupper["tp"].sum()+groupper["fn"].sum())
    recall = recall.fillna(0).mean()

    return precision, recall

In [17]:
compute_cls_metrics(events_recs_for_binary_metrics) # k=5

(0.007581376853347184, 0.014121568795222568)

In [19]:
compute_cls_metrics(events_recs_for_binary_metrics) # k=10

(0.008732947582837622, 0.03130238527136974)

# === Двухстадийный подход: метрики

In [66]:
# покрытие по объектам можно оценить как долю уникальных объектов в рекомендациях (от всех объектов)
# = объект есть в рекомендациях / всего объектов
cov_items  = als_recommendations['item_id'].nunique()/items['item_id'].nunique()
print(f"{cov_items:.2f}")

0.09

In [67]:
# Новизна - доля объектов, ранее не виденных пользователем, среди топ-k рекомендованных:

In [ ]:
# разметим каждую рекомендацию признаком read
events_train["read"] = True
als_recommendations = als_recommendations.merge(events_train[["user_id", "item_id", "read"]], on=["user_id", "item_id"], how="left")

als_recommendations["read"] = als_recommendations["read"].fillna(False).astype("bool")

# проставим ранги
als_recommendations = als_recommendations.sort_values("score", ascending=False)
als_recommendations["rank"] = als_recommendations.groupby("user_id").cumcount() + 1

# посчитаем novelty по пользователям
novelty_5 = (1-als_recommendations.query("rank <= 5").groupby("user_id")["read"].mean())

# посчитаем средний novelty
novelty_5_mean = novelty_5.mean()

/tmp/ipykernel_2360/2333639935.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events_train["read"] = True

# === Двухстадийный подход: модель

In [13]:
# задаём точку разбиения
split_date_for_labels = pd.to_datetime("2017-09-15").date()

split_date_for_labels_idx = events_test["started_at"] < split_date_for_labels
events_labels = events_test[split_date_for_labels_idx].copy()
events_test_2 = events_test[~split_date_for_labels_idx].copy()

In [14]:
events_labels

,user_id,item_id,started_at,read_at,is_read,rating,user_id_enc,item_id_enc
2478098,1000006,29868610,2017-08-30,2017-09-16,True,4,6,42017
2478104,1000006,7445,2017-08-26,2017-08-30,True,4,6,868
2478089,1000006,18812405,2017-08-05,2017-08-19,True,3,6,37138
11383749,1000007,168642,2017-09-05,2017-09-17,True,5,7,9074
11383750,1000007,28257707,2017-08-16,2017-09-06,True,4,7,41610
...,...,...,...,...,...,...,...,...
1285202,1430578,216378,2017-08-27,2017-08-28,True,4,430578,10066
1285203,1430578,6723348,2017-08-02,2017-08-03,True,4,430578,24681
1941753,1430579,27272506,2017-09-03,2017-10-07,True,3,430579,41386
5625380,1430584,23395680,2017-08-09,2017-08-15,True,4,430584,39645
5625376,1430584,18692431,2017-08-02,2017-08-09,True,3,430584,36924

In [10]:
# загружаем рекомендации от двух базовых генераторов
als_recommendations = pd.read_parquet("candidates/training/als_recommendations.parquet")
content_recommendations = pd.read_parquet("candidates/training/content_recommendations.parquet")

candidates = pd.merge(
    als_recommendations[["user_id", "item_id", "score"]].rename(columns={"score": "als_score"}),
    content_recommendations[["user_id", "item_id", "score"]].rename(columns={"score": "cnt_score"}),
    on=["user_id", "item_id"],
    how="outer")

In [15]:
# добавляем таргет к кандидатам со значением:
# — 1 для тех item_id, которые пользователь прочитал
# — 0, для всех остальных 

events_labels["target"] = 1
candidates = candidates.merge(events_labels[["user_id", "item_id", "target"]], 
                              on=["user_id", "item_id"],
                              how="left")
candidates["target"] = candidates["target"].fillna(0).astype("int")

# в кандидатах оставляем только тех пользователей, у которых есть хотя бы один положительный таргет
candidates_to_sample = candidates.groupby("user_id").filter(lambda x: x["target"].sum() > 0)

# для каждого пользователя оставляем только 4 негативных примера
negatives_per_user = 4
candidates_for_train = pd.concat([
    candidates_to_sample.query("target == 1"),
    candidates_to_sample.query("target == 0") \
        .groupby("user_id") \
        .apply(lambda x: x.sample(negatives_per_user, random_state=0))
    ])

In [16]:
from catboost import CatBoostClassifier, Pool

# задаём имена колонок признаков и таргета
features = ['als_score', 'cnt_score']
target = 'target'

# Create the Pool object
train_data = Pool(
    data=candidates_for_train[features], 
    label=candidates_for_train[target])

# инициализируем модель CatBoostClassifier
cb_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    verbose=100,
    random_seed=0
)

# тренируем модель
cb_model.fit(train_data)

0:	learn: 0.6526057	total: 83.2ms	remaining: 1m 23s
100:	learn: 0.5118959	total: 1.83s	remaining: 16.3s
200:	learn: 0.5111710	total: 3.66s	remaining: 14.6s
300:	learn: 0.5105208	total: 5.52s	remaining: 12.8s
400:	learn: 0.5100174	total: 7.42s	remaining: 11.1s
500:	learn: 0.5095747	total: 9.34s	remaining: 9.3s
600:	learn: 0.5091600	total: 11.2s	remaining: 7.44s
700:	learn: 0.5087803	total: 13.1s	remaining: 5.59s
800:	learn: 0.5084220	total: 15s	remaining: 3.73s
900:	learn: 0.5080930	total: 16.9s	remaining: 1.85s
999:	learn: 0.5078081	total: 18.8s	remaining: 0us

In [17]:
# загружаем рекомендации от двух базовых генераторов
als_recommendations_2 = pd.read_parquet("candidates/inference/als_recommendations.parquet")
content_recommendations_2 = pd.read_parquet("candidates/inference/content_recommendations.parquet")

candidates_to_rank = pd.merge(
    als_recommendations_2[["user_id", "item_id", "score"]].rename(columns={"score": "als_score"}),
    content_recommendations_2[["user_id", "item_id", "score"]].rename(columns={"score": "cnt_score"}),
    on=["user_id", "item_id"],
    how="outer")
    
# оставляем только тех пользователей, что есть в тестовой выборке, для экономии ресурсов
candidates_to_rank = candidates_to_rank[candidates_to_rank["user_id"].isin(events_test_2["user_id"].drop_duplicates())]
print(len(candidates_to_rank))

14517152

In [18]:
inference_data = Pool(data=candidates_to_rank[features])
predictions = cb_model.predict_proba(inference_data)

candidates_to_rank["cb_score"] = predictions[:, 1]

# для каждого пользователя проставляем rank, начиная с 1 — это максимальный cb_score
candidates_to_rank = candidates_to_rank.sort_values(["user_id", "cb_score"], ascending=[True, False])
candidates_to_rank["rank"] = candidates_to_rank.groupby("user_id").cumcount() + 1

max_recommendations_per_user = 100
final_recommendations = candidates_to_rank.query("rank <= @max_recommendations_per_user")
final_recommendations

          user_id   item_id  als_score  cnt_score  cb_score  rank
347       1000003     49628   0.446143   0.906649  0.583617     1
300       1000003   7260188   1.129979        NaN  0.509005     2
301       1000003   6148028   1.123475        NaN  0.509005     3
302       1000003   2767052   1.112699        NaN  0.509005     4
320       1000003     43641   0.617602        NaN  0.477032     5
...           ...       ...        ...        ...       ...   ...
43058095  1430580  23705512   0.016477        NaN  0.232760    96
43058096  1430580   6314763   0.016404        NaN  0.232760    97
43058097  1430580  11710373   0.016035        NaN  0.221228    98
43058098  1430580      7445   0.015793        NaN  0.221228    99
43058099  1430580  17802724   0.015771        NaN  0.221228   100

[7519400 rows x 6 columns]

In [41]:
events_inference = pd.concat([events_train, events_labels])

cb_events_recs_for_binary_metrics_5 = process_events_recs_for_binary_metrics(
    events_inference,
    events_test_2,
    final_recommendations.rename(columns={"cb_score": "score"}), 
    top_k=5)

cb_precision_5, cb_recall_5 = compute_cls_metrics(cb_events_recs_for_binary_metrics_5)

print(f"precision: {cb_precision_5:.3f}, recall: {cb_recall_5:.4f}")

Common users: 75194
precision: 0.006, recall: 0.0153

# === Двухстадийный подход: построение признаков

In [19]:
# Посчитаем новый признак — «возраст» книги на основе года публикации. 
items["age"] = 2018 - items["publication_year"]
invalid_age_idx = items["age"] < 0
items.loc[invalid_age_idx, "age"] = np.nan
items["age"] = items["age"].astype("float")

candidates_for_train = candidates_for_train.merge(items[['item_id','age','average_rating']], 
                                                  on=["item_id"],
                                                  how="left")
candidates_to_rank = candidates_to_rank.merge(items[['item_id','age','average_rating']], 
                                               on=["item_id"],
                                               how="left")

candidates_to_rank['age'].median()

In [50]:
def get_user_features(events):
    """ считает пользовательские признаки """
    
    user_features = events.groupby("user_id").agg(
        reading_years=("started_at", lambda x: (x.max()-x.min()).days/365.25),
        books_read=("user_id", "count"),
        rating_avg=("rating", "mean"),
        rating_std=("rating", "std"))
    
    user_features["books_per_year"] = user_features["books_read"] / user_features["reading_years"]
    
    return user_features

In [52]:
user_features_for_train = get_user_features(events_train)
candidates_for_train = candidates_for_train.merge(user_features_for_train, on="user_id", how="left")
  
# оставим только тех пользователей, что есть в тесте, для экономии ресурсов
events_inference = pd.concat([events_train, events_labels])
events_inference = events_inference[events_inference["user_id"].isin(events_test["user_id"].drop_duplicates())]

user_features_for_ranking = get_user_features(events_inference)
candidates_to_rank = candidates_for_train.merge(user_features_for_ranking, on="user_id", how="left")

candidates_for_train["books_read"].median()

In [ ]:
# определяем индексы топ-10 жанров и всех остальных
genres_top_k = 10
genres_top_idx = genres.sort_values("votes", ascending=False).head(genres_top_k).index
genres_others_idx = list(set(genres.index) - set(genres_top_idx))

genres_top_columns = [f"genre_{id}" for id in genres_top_idx]
genres_others_column = "genre_others"
#genres_top_columns.append(genres_others_column)
genre_columns = genres_top_columns+[genres_others_column]

# составляем таблицу принадлежности книг к жанрам
item_genres = (
    pd.concat([
        # топ жанров
        pd.DataFrame(all_items_genres_csr[:, genres_top_idx].toarray(), columns=genres_top_columns),
        # все остальные жанры
        pd.DataFrame(all_items_genres_csr[:, genres_others_idx].sum(axis=1), columns=[genres_others_column])
        ],
        axis=1)
    .reset_index()
    .rename(columns={"index": "item_id_enc"})
)

In [ ]:
# объединяем информацию принадлежности книг к жанрам с основной информацией о книгах
items = items.merge(item_genres, on="item_id_enc", how="left")

def get_user_genres(events, items, item_genre_columns):
    user_genres = (
        events
        .merge(items[["item_id"] + item_genre_columns], on="item_id", how="left")
        .groupby("user_id")[item_genre_columns].mean()
    )
    return user_genres
    
user_genres_for_train = get_user_genres(events_train, items, genre_columns)
candidates_for_train = candidates_for_train.merge(user_genres_for_train, on="user_id", how="left")

user_genres_for_ranking = get_user_genres(events_inference, items, genre_columns)
candidates_to_rank = candidates_to_rank.merge(user_genres_for_ranking, on="user_id", how="left")

In [ ]:
candidates_for_train['genre_34'].median()

In [ ]:
from catboost import CatBoostClassifier, Pool

# задаём имена колонок признаков и таргета
features = ['als_score', 'cnt_score', 
    'age', 'average_rating', 'reading_years', 'books_read', 
    'rating_avg', 'rating_std', 
    'books_per_year'] + genre_columns
target = 'target'

# создаём Pool
train_data = Pool(
    data=candidates_for_train[features], 
    label=candidates_for_train[target])

# инициализируем модель CatBoostClassifier
cb_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    loss_function='Logloss',
    verbose=100,
    random_seed=0,
)

# тренируем модель
cb_model.fit(train_data)

In [ ]:
# Получите топ-100 самых релевантных рекомендация для каждого пользователя, используя обученную модель.

inference_data = Pool(data=candidates_to_rank[features])
predictions = cb_model.predict_proba(inference_data)

candidates_to_rank["cb_score"] = predictions[:,1]
# для каждого пользователя проставим rank, начиная с 1 — это максимальный cb_score
candidates_to_rank = candidates_to_rank.sort_values(["user_id", "cb_score"], ascending=[True, False])
candidates_to_rank["rank"] = candidates_to_rank.groupby("user_id").cumcount() + 1

max_recommendations_per_user = 100
final_recommendations = candidates_to_rank.query("rank <= @max_recommendations_per_user")

final_recommendations['user_id'].nunique()

In [ ]:
final_recommendations.to_parquet("final_recommendations_feat.parquet")

In [ ]:
# Используя отложенную тестовую выборку events_test_2, посчитайте метрики recall и precision для полученных рекомендаций.
# для экономии ресурсов оставим события только тех пользователей, 
# для которых следует оценить рекомендации

events_inference = pd.concat([events_train, events_labels])
events_inference = events_inference[events_inference["user_id"].isin(events_test_2["user_id"].drop_duplicates())]

cb_events_recs_for_binary_metrics_5 = process_events_recs_for_binary_metrics(
    events_inference,
    events_test_2,
    final_recommendations.rename(columns={"cb_score": "score"}), 
    top_k=5)

cb_precision_5, cb_recall_5 = compute_cls_metrics(cb_events_recs_for_binary_metrics_5)

print(f"precision: {cb_precision_5:.3f}, recall: {cb_recall_5:.3f}")

In [ ]:
# код для получения информации о важности признаков.

feature_importance = pd.DataFrame(cb_model.get_feature_importance(), 
    index=features, 
    columns=["fi"])
feature_importance = feature_importance.sort_values(["fi"], ascending=False)
print(feature_importance )